install ack
install ansible
install homebrew/dupes/apple-gcc42
install ctags
install docker
install docker-machine
install erlang
install git
install neovim/neovim/neovim
install nmap
install packer
install python
install rbenv
install rlwrap
install stow
install tmux
install tree
install vim
install z
install zsh
